name: Battle Game CI/CD

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  build-and-test:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [3.12.2]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run tests
        run: |
          py -m unittest
          echo "Tests executed"

      - name: Handle test results
        if: failure()
        run: |
          git reset --hard HEAD~1
          git checkout -b failures/${{ github.run_number }}
          git push origin failures/${{ github.run_number }}
          echo "Test failed, rolled back and pushed to failures branch"

      - name: Merge develop to main
        if: success()
        run: |
          git config --global user.email paul.bardou@live.fr
          git config --global user.name paul-brd02
          git fetch
          git checkout main
          git pull origin main
          git merge develop --allow-unrelated-histories --strategy-option theirs
          git push origin main || true
          
          echo "Test passed, merged to main"  
